version = 1

exclude_patterns = [
  "**/venv/**",
  "**/__pycache__/**",
  "**/node_modules/**",
  "**/build/**",
  "**/dist/**"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["jest"]