version = 1

# Exclude folders that shouldn't be scanned
exclude_patterns = [
  "**/venv/**",
  "**/__pycache__/**",
  "**/node_modules/**",
  "**/build/**",
  "**/dist/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x"
  # This tells DeepSource where your Python code lives
  test_patterns = ["flask-mysql-crud/tests/**"] 

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  runtime_version = "18"

[autofix]
enabled = true